---
title: "QPM 1: Pset 1 (R Coding)"
author: "Bort Wu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 3

# a)
```{r}
library(ggplot2)
# Generate a range of numbers from -10 to 10
z <- seq(from = -10, to = 10, by = 0.001)

# Define the function f(z) = exp(-z^2)
ez <- function(x){
  ez <- exp(-x^2)
  return(ez)
}

# Create a data frame with z and f(z)
data.ez <- data.frame(x = z, y = ez(z))

# Add a column to identify the area color
data.ez$area <- ifelse(data.ez$x < 0, "red", "blue")

# Plot using ggplot2
ggplot(data.ez, aes(x = x, y = y, fill = area)) +
  geom_area(alpha = 0.5) +  # Fill the areas under the curve with transparency
  scale_fill_identity() +   # Use the 'fill' column directly for colors
  theme_minimal() +
  labs(
    title = "Plot of f(z) = exp(-z^2)",
    x = "z",
    y = "f(z)",
    fill = "Area"
  ) +
  theme(legend.position = "none")

```

## Question 5: Simulation of Law of Large Numbers

```{r}

# Generate a sample of 5000 coin flips 
#with probability of heads facing up p = 0.5
set.seed(12345)
N <- 5000 #Number of coin flips

samp <- rbinom(N, size = 1, prob = 0.5) #Sample 5000 coin flips

# Calculate the frequency of heads up to each coin flip
flips <- cumsum(samp) # Cumulative summation of numbers of heads

y <- cumsum(samp)/(1:N)

# Create a dataframe with x being the index of each coin flip 
#and y being the result of each coin flip.
data.lln <- data.frame(x = 1:N, y = y)

ggplot(data = data.lln, aes(x=x, y=y))+
  geom_line(color = "red") +
  annotate("segment", x = 0, xend = 5000, y = c(0.5,0.51,0.49), 
           yend = c(0.5,0.51,0.49), linetype = "dashed", color = "black")+
  ylim(0,1)+ xlim(0,5000)+
  labs(title = "Law of Large Numbers: Convergence of Heads Frequency",
       x = "Sample Size",
       y = "Proportion of Heads") +
  theme_minimal()

```


